'use strict';

/**
 * Seed data — realistic Czech news articles for demo/offline mode.
 * Used automatically when live RSS feeds are unreachable.
 */
const SEED_ARTICLES = [
  {
    source: 'iROZHLAS',
    url: 'https://www.irozhlas.cz/zpravy-domov/parlament-hlasovani-rozpocet-2025',
    title: 'Sněmovna schválila státní rozpočet na rok 2025 s deficitem 270 miliard korun',
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    author: 'Jan Novák',
    rubric: 'zpravy-domov',
    text: 'Poslanecká sněmovna ve čtvrtek schválila státní rozpočet na příští rok s plánovaným schodkem 270 miliard korun. Pro návrh hlasovalo 104 poslanců vládní koalice, proti bylo 84 poslanců opozice. Ministr financí Zbyněk Stanjura označil rozpočet za odpovědný krok v obtížné ekonomické situaci. Opozice naopak kritizovala výši deficitu a upozorňovala na riziko dalšího zadlužování státu. Rozpočet počítá s příjmy ve výši 1 960 miliard korun a výdaji přesahujícími 2 230 miliard korun. Největší položkou výdajů zůstávají sociální transfery a výdaje na zdravotnictví. Vláda argumentuje tím, že část deficitu tvoří jednorázové investiční výdaje, zejména do infrastruktury a obrany. Kritici ovšem poukazují na to, že strukturální deficit zůstává vysoký i po očištění o tyto položky. Senát bude o rozpočtu jednat příští týden, přestože horní komora parlamentu nemá pravomoc jej zablokovat. Prezident republiky by jej měl podepsat ještě před koncem roku.',
  },
  {
    source: 'iROZHLAS',
    url: 'https://www.irozhlas.cz/veda-technologie/umela-inteligence-regulace-eu-2025',
    title: 'Evropská unie spustila první fázi regulace umělé inteligence. Co to znamená pro firmy?',
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    author: 'Petra Horáčková',
    rubric: 'veda-technologie',
    text: 'Od prvního srpna vstoupila v platnost první část evropského nařízení o umělé inteligenci, které EU přijala loni. Nová pravidla se zatím týkají především systémů klasifikovaných jako nepřijatelné riziko, tedy například technologií rozpoznávání tváří na veřejných prostranstvích nebo systémů hodnocení sociálního chování. Firmy, které tyto technologie provozují, musí okamžitě ukončit jejich provoz nebo získat výjimku. Odborníci upozorňují, že implementace nařízení bude složitá zejména pro menší podniky, které nemají kapacity na právní a technický compliance. Česká agentura pro digitální inovace vydala metodický pokyn, který má firmám pomoci se orientovat v nových povinnostech. Druhá vlna regulace, týkající se systémů s vysokým rizikem jako jsou nástroje pro přijímání zaměstnanců nebo systémy používané ve zdravotnictví, vstoupí v platnost za dva roky. Experti diskutují o tom, zda evropská regulace nezpomalí inovace v oblasti AI ve srovnání s USA a Čínou, kde jsou pravidla volnější. Zastánci nařízení naopak tvrdí, že jasná pravidla zvýší důvěru veřejnosti v AI systémy a v dlouhodobém horizontu podpoří jejich adopci.',
  },
  {
    source: 'iROZHLAS',
    url: 'https://www.irozhlas.cz/zpravy-svet/konflikt-ukraine-rusko-fronts',
    title: 'Situace na frontě na Ukrajině: intenzivní boje pokračují v Záporožské oblasti',
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    author: 'Tomáš Vlček',
    rubric: 'zpravy-svet',
    text: 'Na východní Ukrajině pokračují těžké boje zejména v Záporožské a Charkovské oblasti. Ruské síly se pokoušejí o postup podél několika os, ukrajinská obrana však hlásí úspěšné odrážení útoků. Generální štáb ozbrojených sil Ukrajiny informoval o více než devadesáti střetech za poslední den. Situace je mimořádně napjatá v okolí Toretsku, kde se frontová linie stabilizovala po několika týdnech intenzivních bojů. Mezinárodní pozorovatelé upozorňují na rostoucí opotřebení obou armád a na nutnost dalšího zásobování Ukrajiny municí a zbrojním materiálem. Americký kongres schválil nový balíček vojenské pomoci ve výši 61 miliard dolarů, jehož distribuce však potrvá několik týdnů. Diplomatické pokusy o zahájení mírových rozhovorů zatím nepřinesly výsledky, přičemž obě strany trvají na podmínkách, které jsou pro druhou stranu nepřijatelné. Humanitární situace v příhraničních oblastech zůstává kritická, tisíce civilistů jsou nuceny opouštět své domovy.',
  },
  {
    source: 'iROZHLAS',
    url: 'https://www.irozhlas.cz/ekonomika/inflace-ceska-republika-statistiky',
    title: 'Inflace v Česku zpomalila na 2,4 procenta. Ekonomové čekají další pokles',
    published_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    author: 'Marie Součková',
    rubric: 'ekonomika',
    text: 'Meziroční inflace v České republice zpomalila v říjnu na 2,4 procenta z loňských 2,7 procenta. Vyplývá to z dat Českého statistického úřadu zveřejněných v pátek. Největší vliv na cenový vývoj měly ceny potravin, které meziměsíčně vzrostly o 0,3 procenta, a ceny energií, které naopak mírně klesly. Ekonomové centrální banky se vyjádřili, že inflace se pohybuje v souladu s prognózami a prostor pro případné snižování úrokových sazeb se postupně otevírá. Česká národní banka na posledním zasedání bankovní rady ponechala základní úrokovou sazbu beze změny na úrovni 3,75 procenta. Guvernér Aleš Michl naznačil, že v prvním čtvrtletí příštího roku by mohlo dojít k dalšímu uvolnění měnové politiky, pokud inflační tlaky nepřekvapí. Spotřebitelé však zatím úlevu příliš nepociťují, neboť ceny zůstávají v absolutním vyjádření výrazně vyšší než před inflační vlnou v letech 2021 až 2023.',
  },
  {
    source: 'iROZHLAS',
    url: 'https://www.irozhlas.cz/zpravy-domov/volby-komunalni-vysledky-analyz',
    title: 'Analýza komunálních voleb: vládní strany oslabily, ANO potvrdilo pozici lídra',
    published_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    author: 'Pavel Horák',
    rubric: 'zpravy-domov',
    text: 'Komunální volby přinesly výrazné přeskupení na politické mapě českých měst a obcí. Hnutí ANO potvrdilo svou pozici nejsilnější politické síly a v řadě měst výrazně posílilo. Naopak strany vládní koalice, zejména ODS a Piráti, zaznamenaly ve větších městech pokles preferencí. Sociologové tento trend interpretují jako projev nespokojenosti části voličů s vývojem životní úrovně a inflací posledních let. V Praze se situace lišila od celostátního průměru, kde prokoalicní seskupení udrželo silné pozice. Zajímavým jevem bylo posílení místních uskupení bez stranické příslušnosti, které kandidovaly s programem konkrétních lokálních problémů. Volební účast dosáhla 44 procent, což je o dva procentní body více než v předchozích komunálních volbách. Experti na politologii upozorňují, že výsledky komunálních voleb nelze mechanicky přenášet na celostátní preference, nicméně signalizují určitý posun nálad ve společnosti.',
  },
  {
    source: 'ČT24',
    url: 'https://ct24.ceskatelevize.cz/domaci/skolstvi-reforma-digitalizace',
    title: 'Ministerstvo školství představilo plán digitalizace výuky. Tablety pro každého žáka do tří let',
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    author: 'Kateřina Malá',
    rubric: 'domaci',
    text: 'Ministerstvo školství, mládeže a tělovýchovy dnes zveřejnilo ambiciózní plán digitalizace českého školství. Klíčovým cílem je zajistit do roku 2027 každému žákovi základní školy přístup k vlastnímu digitálnímu zařízení, nejčastěji tabletu nebo notebooku. Součástí plánu je také rozsáhlá modernizace internetové infrastruktury ve školách, přičemž ministerstvo plánuje pokrýt rychlým internetem všechny základní a střední školy v zemi. Odhadované náklady na realizaci přesahují 15 miliard korun, přičemž část prostředků má pocházet z evropských fondů. Učitelské odbory plán přivítaly, ale zároveň upozornily na nutnost souběžného proškolení pedagogů v oblasti digitální didaktiky. Podle výzkumů totiž pouhé zavedení technologií bez odpovídající pedagogické přípravy nevede k zlepšení vzdělávacích výsledků. Opozice kritizuje zejména financování projektu a požaduje podrobnější harmonogram s jasnými kontrolními milníky. Pilotní program bude spuštěn v lednu příštího roku ve vybraných školách v pěti krajích.',
  },
  {
    source: 'ČT24',
    url: 'https://ct24.ceskatelevize.cz/svet/klimaticka-konference-cop-vysledky',
    title: 'Klimatická konference COP29 skončila kompromisem. Bohaté státy slíbily více peněz chudým zemím',
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    author: 'Radek Šimánek',
    rubric: 'svet',
    text: 'Mezinárodní klimatická konference COP29 v Baku skončila po náročných dvoutýdenních jednáních přijetím dohody o financování klimatické adaptace v rozvojových zemích. Vyspělé státy se zavázaly do roku 2035 poskytovat ročně 300 miliard dolarů na klimatická opatření v nejchudších částech světa. Klimatičtí aktivisté označili výsledek za zcela nedostatečný, protože původní požadavky rozvojových zemí dosahovaly 1 300 miliard dolarů ročně. Zástupci malých ostrovních států vyjádřili hořké zklamání a upozornili, že bez masivnějšího financování adaptačních opatření hrozí jejich zemím do konce století záplavy a zánik. Vědecká komunita zdůraznila, že i s přijatými závazky planeta míří k oteplení o 2,5 stupně Celsia nad předindustriální úrovní, což výrazně překračuje cíle Pařížské dohody. Příští konference COP30 se uskuteční v brazilském Belému a bude se zabývat konkrétními mechanismy implementace přijatých závazků.',
  },
  {
    source: 'ČT24',
    url: 'https://ct24.ceskatelevize.cz/domaci/zdravotnictvi-cekacidoby-reforma',
    title: 'Čekací doby na operace se prodloužily. Zdravotnictví trápí nedostatek lékařů i sester',
    published_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    author: 'Lucie Horáková',
    rubric: 'domaci',
    text: 'Čekací doby na plánované operace v českých nemocnicích se v průběhu letošního roku výrazně prodloužily. Průměrná doba čekání na výměnu kyčelního nebo kolenního kloubu nyní přesahuje 14 měsíců, u některých výkonů i dva roky. Ministerstvo zdravotnictví přiznává, že situace je vážná a je způsobena kombinací několika faktorů. Primárním problémem je nedostatek zdravotnického personálu, zejména operačních sester a anesteziologů. Průměrný věk lékaře v Česku překračuje 50 let a podíl lékařů odcházejících do zahraničí za lepšími platovými podmínkami zůstává vysoký. Vláda schválila navýšení tarifních mezd ve zdravotnictví o 10 procent, ale odborové organizace to považují za nedostatečné. Česká lékařská komora varuje, že bez systémových změn ve financování zdravotnictví a odměňování zdravotníků bude situace v příštích letech ještě horší. Pacienti stěžující si na nepřiměřeně dlouhé čekání mohou za určitých podmínek žádat o přeshraniční péči v rámci EU.',
  },
  {
    source: 'ČT24',
    url: 'https://ct24.ceskatelevize.cz/svet/technologie-elektromobily-trh',
    title: 'Prodeje elektromobilů v Evropě klesají. Výrobci volají po zachování dotací',
    published_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    author: null,
    rubric: 'svet',
    text: 'Prodeje nových elektromobilů v Evropské unii meziročně poklesly o sedm procent, vyplývá z dat Evropské asociace výrobců automobilů. Jde o první výraznější pokles od roku 2020, kdy se elektromobily začaly masivněji prosazovat na trhu. Výrobci jako Volkswagen, Stellantis a Renault upozorňují, že bez zachování státních pobídek a dotací nelze očekávat splnění evropských cílů v oblasti elektrifikace dopravy. Brusel trvá na tom, že od roku 2035 nesmějí být v EU prodávány nové automobily se spalovacím motorem. Kritici tohoto plánu poukazují na nedostatečnou nabíjecí infrastrukturu, vysoké ceny elektromobilů a omezený dojezd baterií, zejména v zimních podmínkách. Čínští výrobci, zejména BYD a SAIC, mezitím agresivně vstupují na evropský trh s vozy, jejichž cena je výrazně nižší než u evropské konkurence. Evropská komise zahájila antidumpingové šetření a zvažuje zavedení cel na čínské elektromobily.',
  },
  {
    source: 'ČT24',
    url: 'https://ct24.ceskatelevize.cz/sport/fotbal-reprezentace-euro-kvalifikace',
    title: 'Česká fotbalová reprezentace porazila Albánii 2:1 a přiblížila se postupu na mistrovství Evropy',
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    author: 'Ondřej Kovář',
    rubric: 'sport',
    text: 'Česká fotbalová reprezentace zvítězila v kvalifikačním utkání o postup na mistrovství Evropy nad Albánií 2:1. Rozhodující gól vstřelil v 78. minutě Tomáš Souček hlavičkou po rohovém kopu. Národní tým tak poskočil na druhé místo v tabulce skupiny a má dobrou výchozí pozici před posledními dvěma zápasy kvalifikace. Trenér Ivan Hašek pochválil kolektivní výkon mužstva, zejména v defenzivní fázi hry. Albánie sice vedla po první půli 1:0 po rychlém brejku, ale česká reprezentace dokázala otočit výsledek díky vyrovnanému výkonu ve druhém poločase. Klíčovým zápasem bude říjnové derby se Slovenskem, které je v tabulce na prvním místě. Případná výhra nad sousedy by reprezentaci prakticky zajistila přímý postup na šampionát. Fanoušci v plném Edenu povzbudivě skandovali po celý zápas a věří, že tým uspěje v boji o místo na Euru.',
  },
  {
    source: 'Novinky.cz',
    url: 'https://www.novinky.cz/domaci/clanek/koalice-programove-prohlaseni-vlady',
    title: 'Koaliční strany se dohodly na programovém prohlášení vlády. Prioritou je snižování dluhu',
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    author: 'Jakub Procházka',
    rubric: 'domaci',
    text: 'Pět vládních stran se v pondělí dohodlo na finálním znění programového prohlášení vlády na příští volební období. Klíčovou prioritou má být postupné snižování státního dluhu a stabilizace veřejných financí. Vláda se zavázala každoročně snižovat strukturální deficit o minimálně 0,5 procenta HDP. Druhá priorita se týká oblasti bezpečnosti a obrany, přičemž kabinet potvrdil závazek zvyšovat výdaje na obranu tak, aby do roku 2030 dosáhly dvou procent HDP v souladu s požadavky NATO. Ve třetí prioritě se koalice zaměřuje na transformaci české ekonomiky směrem k průmyslu s vyšší přidanou hodnotou a na podporu domácího výzkumu a inovací. Sociální oblast zahrnuje závazek zachovat reálnou hodnotu důchodů a zvyšovat dostupnost bydlení prostřednictvím nové státní bytové politiky. Opozice programové prohlášení označila za sborník prázdných frází bez konkrétních čísel a harmonogramů.',
  },
  {
    source: 'Novinky.cz',
    url: 'https://www.novinky.cz/zahranicni/clanek/biden-trump-zahranicni-politika',
    title: 'Trump po návratu do Bílého domu mění americkou zahraniční politiku. Co to znamená pro Evropu?',
    published_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    author: 'Eva Nováčková',
    rubric: 'zahranicni',
    text: 'Návrat Donalda Trumpa do Oválné pracovny přináší výraznou změnu v orientaci americké zahraniční politiky. Nová administrativa dává zřetelně najevo, že hodlá přezkoumat míru amerického angažmá v evropské bezpečnosti a požaduje, aby evropské státy výrazně zvýšily vlastní výdaje na obranu. Trump opakovaně naznačil, že USA by mohly přehodnotit svůj závazek hájit spojence v NATO, pokud nebudou plnit alianční cíle v oblasti obranných výdajů. Pro Evropu to znamená nutnost zrychlit budování vlastních obranných kapacit. Německo, které bylo historicky nejzdrženlivější v otázkách militarizace, schválilo rekordní navýšení obranného rozpočtu. Francouzský prezident Macron opakovaně volá po vytvoření skutečně autonomní evropské obrany. Analytici se rozcházejí v tom, zda jde o skutečný strategický posun, nebo o vyjednávací taktiku. Jisté je, že transatlantické vztahy vstupují do nové fáze, která bude vyžadovat výrazně větší strategickou autonomii Evropy.',
  },
  {
    source: 'Novinky.cz',
    url: 'https://www.novinky.cz/domaci/clanek/byidleni-ceny-nemovitosti-2025',
    title: 'Ceny bytů v Praze opět rostou. Průměrná cena za metr čtvereční překročila 130 000 korun',
    published_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    author: 'Václav Beneš',
    rubric: 'domaci',
    text: 'Ceny bytů v hlavním městě znovu akcelerují po krátkém ochlazení trhu v roce 2023. Průměrná nabídková cena novostavby v Praze překročila 130 000 korun za metr čtvereční, vyplývá z aktuální analýzy realitní kanceláře. Starší byty jsou v průměru levnější, nicméně i jejich cena se za posledních 12 měsíců zvýšila o šest procent. Hypoteční sazby sice klesly z maxim, ale stále se pohybují kolem pěti procent, takže dostupnost vlastního bydlení pro mladé rodiny zůstává problematická. Průměrná Praha odmítá přijatý územní plán, který by umožnil výstavbu na okrajích města a mohl by nabídku bytů zvýšit. Experti upozorňují, že bez zásadního urychlení povolování nové výstavby nelze situaci systémově řešit. Nájemní bydlení sice nabízí alternativu, ale průměrný nájem za byt 2+1 v Praze přesahuje 20 000 korun měsíčně, což je pro mnohé domácnosti neúnosné. Vláda připravuje zákon o dostupném bydlení, jehož konkrétní podoba je zatím předmětem koaličních jednání.',
  },
  {
    source: 'Novinky.cz',
    url: 'https://www.novinky.cz/zahranicni/clanek/blizky-vychod-izrael-hamas-primeri',
    title: 'Příměří v Gaze: zprostředkovatelé hlásí pokrok v jednáních, ale dohoda stále není jistá',
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    author: null,
    rubric: 'zahranicni',
    text: 'Jednání o příměří v Gaze vstoupila do kritické fáze. Katarští a egyptští zprostředkovatelé informují o dílčím pokroku, ale upozorňují, že klíčové otázky zůstávají nevyřešeny. Izrael trvá na zachování vojenské přítomnosti v koridoru Philadelphi podél hranice s Egyptem, s čímž Hamas nesouhlasí. Sporná je také otázka propuštění izraelských rukojmích výměnou za palestinské vězně. Humanitární situace v Gaze zůstává katastrofální, mezinárodní organizace varují před hrozícím hladomorem v severní části pásma. USA intenzivně tlačí na obě strany, aby přijaly kompromisní řešení. Americký ministr zahraničí absolvoval v posledních dnech sérii setkání v regionu. Analytici upozorňují, že i v případě dosažení příměří bude poválečná situace v Gaze extrémně složitá a otázka správy území zůstává bez odpovědi.',
  },
  {
    source: 'Novinky.cz',
    url: 'https://www.novinky.cz/domaci/clanek/sucho-voda-klima-cesko-prognoza',
    title: 'Česko se musí připravit na opakující se sucha. Vědci varují před nedostatkem vody do roku 2050',
    published_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    author: 'Tereza Holubová',
    rubric: 'domaci',
    text: 'Klimatologové z Akademie věd České republiky varují, že bez zásadních adaptačních opatření bude Česko v horizontu 25 let čelit vážným problémům s dostupností pitné vody. Scénáře klimatických modelů předpovídají výrazné zvýšení průměrných teplot a změnu srážkového režimu, přičemž léta budou výrazně sušší, zatímco v zimě bude docházet k intenzivnějším srážkám. Klíčovým problémem je schopnost krajiny zadržovat vodu. Meliorace provedené v druhé polovině 20. století výrazně zrychlily odtok vody z polí a luk. Revitalizace toků, obnova mokřadů a změna zemědělských postupů jsou opatření, která mohou situaci zlepšit, ale jejich implementace je pomalá a nákladná. Správci vodohospodářské infrastruktury upozorňují na zastaralost distribuční sítě a na nutnost masivních investic do modernizace vodovodů a čistíren odpadních vod. Vláda připravuje Národní vodohospodářský plán, který by měl koordinovat investice a regulaci v tomto sektoru na příštích deset let.',
  },
];

module.exports = { SEED_ARTICLES };
